### ISSUE TITLE
Implement McICA to handle partial cloud fraction

### ISSUE THREAD

**Issue by szy21** [CliMA/RRTMGP.jl#296]
## Purpose
Implement McICA to allow partial cloud fraction when calculating all-sky radiative fluxes

## Cost/Benefits/Risks
Benefits: We need it for a good AMIP simulation
Risks: There is no example in the original RRTMGP, so it won't be a direct translation. We also need to find tests elsewhere (e.g. from RRTMG).

## People and Personnel
(@ the personnel required/requested to implement the software solution)
- Lead: @sriharshakandala 
- Collaborators: @szy21 
- Reviewers: @szy21 @tapios (if needed)

## Components
(Describe the main components of the software solution)
Translate `draw samples`, `sampled_mask_max_ran`, `apply_cloud_mask` from [here](https://github.com/earth-system-radiation/rte-rrtmgp/blob/main/extensions/cloud_optics/mo_cloud_sampling.F90)
Use `draw samples` to map cloud optics from bands to g-points (how do we get cloud optics by bands now?)
Use the existing[ `add_cloud_optics_2stream` ](https://github.com/CliMA/RRTMGP.jl/blob/e5c0c735a68bc2fff965fce1b9d066ffea17d6b1/src/optics/CloudOptics.jl#L38)to add cloud optics

## Results and deliverables
New RRTMGP release with partial cloud fraction functionality
An example using McICA (probably from RRTMG)

## Proposed Delivery Date
July 15, 2022

**Comment by sriharshakandala** [comment]
## Task breakdown
- [ ] Refine/enlarge cloud_mask to be g-point and long/shortwave specific
- [ ] Add user prescribable cloud fraction input for long/shortwave calculations
- [ ] Add random number generator to build cloud mask for a given cloud fraction
- [ ] Add an all-sky test with non-trivial cloud fraction, compare it with RRTMGP data
