### ISSUE TITLE
Update `LookUp` tables and reference datasets

### ISSUE THREAD

**Issue by sriharshakandala** [CliMA/RRTMGP.jl#481]
Update `LookUp` tables and reference datasets to match with version `1.7` or RRTMGP https://github.com/earth-system-radiation/rte-rrtmgp

cc: @szy21 
```[tasklist]
### Tasks
- [x] Temporarily bypass `Artifacts`, use the latest `lookup` tables and reference datasets
- [x] Test code with latest lookup tables for any differences
- [ ] If differences are noticed, locally install FORTRAN code, identify source code and test input data differences
- [x] Make appropriate source code source code modifications
- [x] <https://github.com/CliMA/RRTMGP.jl/pull/492>
- [ ] https://github.com/CliMA/RRTMGP.jl/pull/495
- [ ] https://github.com/CliMA/RRTMGP.jl/pull/498
- [ ] https://github.com/CliMA/RRTMGP.jl/pull/493
- [ ] https://github.com/CliMA/RRTMGP.jl/pull/499
- [ ] Add non-scattering longwave solver with rescaling
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by szy21** [comment]
I think we can close this.
